// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD9bGPCy-hgY_ecEv3youE5tkFNT1RoD0',
    appId: '1:224274136821:web:4c3a1908cce4744ed24fbc',
    messagingSenderId: '224274136821',
    projectId: 'oneclick-22a1d',
    authDomain: 'oneclick-22a1d.firebaseapp.com',
    storageBucket: 'oneclick-22a1d.appspot.com',
    measurementId: 'G-H70J33F8V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhRQkh3hDMhCezmHaTa-dag0j0zzd7XCQ',
    appId: '1:224274136821:android:6d105f8658b12d29d24fbc',
    messagingSenderId: '224274136821',
    projectId: 'oneclick-22a1d',
    storageBucket: 'oneclick-22a1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxvV8d0snHk5Ns2iyWJJHeDJXgK9EesKA',
    appId: '1:224274136821:ios:e8a59c8d435da43bd24fbc',
    messagingSenderId: '224274136821',
    projectId: 'oneclick-22a1d',
    storageBucket: 'oneclick-22a1d.appspot.com',
    iosClientId: '224274136821-77stbhf0gjl812cmqn3rqh3co4h7fcor.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneclickv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxvV8d0snHk5Ns2iyWJJHeDJXgK9EesKA',
    appId: '1:224274136821:ios:e8a59c8d435da43bd24fbc',
    messagingSenderId: '224274136821',
    projectId: 'oneclick-22a1d',
    storageBucket: 'oneclick-22a1d.appspot.com',
    iosClientId: '224274136821-77stbhf0gjl812cmqn3rqh3co4h7fcor.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneclickv2',
  );
}
